services:
  mongo-primary:
    image: mongo:latest
    container_name: mongo-primary
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    networks:
      - mongo-cluster

  mongo-secondary-1:
    image: mongo:latest
    container_name: mongo-secondary-1
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27018:27017"
    networks:
      - mongo-cluster

  mongo-secondary-2:
    image: mongo:latest
    container_name: mongo-secondary-2
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27019:27017"
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    driver: bridge
